openapi: 3.1.0
info:
  title: Patchpump api specification
  description: Patchpump api specification
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /{api_version}/users: {}
  /{api_version}/users/{user_id}: {}
  /{api_version}/users/{user_id}/actives: {}
  /{api_version}/users/{user_id}/organizations: {}
  /{api_version}/users/{user_id}/roles: {}
  /{api_version}/users/{user_id}/files: {}
  /{api_version}/users/{user_id}/files/{file_id}: {}
  /{api_version}/users/{user_id}/notifications: {}
  /{api_version}/actives: {}
  /{api_version}/actives/{active_id}: {}
  /{api_version}/actives/{active_id}/programs: {}
  /{api_version}/actives/{active_id}/users: {}
  /{api_version}/actives/{active_id}/vulnerabilities: {}
  /{api_version}/programs: {}
  /{api_version}/programs/{id}: {}
  /{api_version}/organizations: {}
  /{api_version}/organizations/{org_id}: {}
  /{api_version}/organizations/{org_id}/actives: {}
  /{api_version}/organizations/{org_id}/programs: {}
  /{api_version}/organizations/{org_id}/vulnerabilities: {}
  /{api_version}/organizations/{org_id}/employees: {}
  /{api_version}/organizations/{org_id}/files: {}
  /{api_version}/organizations/{org_id}/notifications: {}
  /{api_version}/vulnerabilities: {}
  /{api_version}/vulnerabilities/cwe: {}
  /{api_version}/vulnerabilities/cve-{id}: {}
  /{api_version}/vulnerabilities/bdu-{id}: {}
  /{api_version}/files: {}
  /{api_version}/files/id: {}
  /{api_version}/notifications: {}
  /{api_version}/notifications/{notification_id}: {}
